name: CI
on:
- push
- pull_request
jobs:
  xenial:
    container: 
      image: vapor/swift:5.1-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery
  # swift55:
  #   container: 
  #     image: swift:5.5
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: swift test
  bionic:
    container: 
      image: vapor/swift:5.1-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Bionic Tests
      run: swift test --enable-test-discovery --enable-code-coverage
    - name: Setup container for codecov upload
      run: apt-get update && apt-get install curl -y
    - name: Process coverage file
      run: llvm-cov show .build/x86_64-unknown-linux/debug/SwiftMarkdownPackageTests.xctest -instr-profile=.build/x86_64-unknown-linux/debug/codecov/default.profdata > coverage.txt
    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_UPLOAD_KEY }}
        file: coverage.txt
